"""
llm_watcher.py — RAG Threat Detector core pipeline
====================================================
Reads all configuration from config.yaml (generated by setup_wizard.py).
No hardcoded values — every setting comes from config.

Pipeline per log:
  1. Poll ES for unanalyzed logs
  2. Build session behavioral summary (±window minutes, same src_ip)
  3. Retrieve top-k MITRE+Sigma techniques via ChromaDB RAG
  4. Get baseline deviation context per IP
  5. Send all context to LLM for zero-shot threat reasoning
  6. Write verdict back to ES with attack type, MITRE ID, confidence

Supported LLM providers: Ollama, DeepSeek, Claude
"""

import time
import yaml
import requests
import chromadb
from pathlib import Path
from sentence_transformers import SentenceTransformer
from elasticsearch import Elasticsearch
from baseline import BaselineModel

CONFIG_FILE = "./config.yaml"


# ── Load config ───────────────────────────────────────────────────────────────
def load_config() -> dict:
    if not Path(CONFIG_FILE).exists():
        print(f"[!] Config not found: {CONFIG_FILE}")
        print("    Run: python main.py --setup")
        raise SystemExit(1)
    with open(CONFIG_FILE) as f:
        return yaml.safe_load(f)


cfg = load_config()

# ── Config values — all from config.yaml ──────────────────────────────────────
ES_HOST    = cfg["elasticsearch"]["host"]
ES_USER    = cfg["elasticsearch"].get("username", "")
ES_PASS    = cfg["elasticsearch"].get("password", "")
RAW_INDEX  = cfg["elasticsearch"]["index"]
OUT_INDEX  = cfg["output"]["analyzed_index"]
REVIEW_INDEX = OUT_INDEX + "-review"

LLM_PROVIDER  = cfg["llm"]["provider"]
OLLAMA_HOST   = cfg["llm"].get("ollama_host", "http://localhost:11434")
OLLAMA_MODEL  = cfg["llm"].get("ollama_model", "qwen3:14b")
DS_API_KEY    = cfg["llm"].get("deepseek_api_key", "")
CL_API_KEY    = cfg["llm"].get("claude_api_key", "")
CL_MODEL      = cfg["llm"].get("claude_model", "claude-sonnet-4-6")

DB_PATH    = cfg["rag"]["db_path"]
COLLECTION = cfg["rag"]["collection"]
EMBED_MODEL= cfg["rag"]["embed_model"]
TOP_K      = cfg["analysis"].get("top_k_chunks", 4)

SESSION_WINDOW_MINUTES = cfg["analysis"]["session_window_minutes"]
POLL_EVERY             = cfg["analysis"]["poll_interval_seconds"]

BASELINE_MODE   = cfg["baseline"]["mode"]
BASELINE_HOURS  = cfg["baseline"].get("hours", 2)
BASELINE_BEFORE = cfg["baseline"].get("before")

# Per-log-type confidence thresholds
LOG_TYPE      = cfg.get("log_type", "linux")
THRESHOLDS    = {"linux": "HIGH", "windows": "MEDIUM", "firewall": "MEDIUM"}
MIN_CONFIDENCE = THRESHOLDS.get(LOG_TYPE, "HIGH")

# ── Init clients ──────────────────────────────────────────────────────────────
if ES_USER and ES_PASS:
    es = Elasticsearch(ES_HOST, basic_auth=(ES_USER, ES_PASS))
else:
    es = Elasticsearch(ES_HOST)

embedder   = SentenceTransformer(EMBED_MODEL)
chroma     = chromadb.PersistentClient(path=DB_PATH)
collection = chroma.get_collection(COLLECTION)

# ── Init baseline ──────────────────────────────────────────────────────────────
baseline = BaselineModel(es)
if not baseline.load("./baseline.json"):
    before = BASELINE_BEFORE
    if BASELINE_MODE == "auto" or not before:
        from datetime import datetime, timezone
        before = datetime.now(timezone.utc).isoformat()
    baseline.build(index=RAW_INDEX, hours=BASELINE_HOURS, before_timestamp=before)
    baseline.save("./baseline.json")

# ── Startup banner ────────────────────────────────────────────────────────────
llm_label = LLM_PROVIDER
if LLM_PROVIDER == "ollama":
    llm_label = f"ollama / {OLLAMA_MODEL}"
elif LLM_PROVIDER == "deepseek":
    llm_label = "deepseek-chat (cloud)"
elif LLM_PROVIDER == "claude":
    llm_label = f"claude / {CL_MODEL}"

print(f"RAG ready         — {collection.count()} entries (MITRE + Sigma)")
print(f"LLM               — {llm_label}")
print(f"Embedder          — {EMBED_MODEL}")
print(f"Log server        — {ES_HOST}")
print(f"Polling index     — {RAW_INDEX}")
print(f"Output index      — {OUT_INDEX}")
print(f"Log type          — {LOG_TYPE} (min confidence: {MIN_CONFIDENCE})")
print(f"Session window    — ±{SESSION_WINDOW_MINUTES} min")
print(f"Baseline          — {len(baseline.baseline)} IPs profiled\n")


# ── RAG retrieval ─────────────────────────────────────────────────────────────
def retrieve_mitre(log_text: str) -> str:
    vec = embedder.encode(log_text).tolist()
    res = collection.query(query_embeddings=[vec], n_results=TOP_K)
    out = []
    for i in range(len(res["ids"][0])):
        m = res["metadatas"][0][i]
        d = res["documents"][0][i]
        out.append(f"[{m['id']}] {m['technique']} ({m['tactic']}): {d[:150]}")
    return "\n".join(out)


# ── Session grouping ──────────────────────────────────────────────────────────
def get_session(focus_hit: dict) -> tuple[str, dict]:
    ts     = focus_hit["_source"].get("@timestamp", "")
    src_ip = focus_hit["_source"].get("src_ip", "")

    if not src_ip:
        return _get_time_neighbors(ts), {}

    try:
        res = es.search(index=RAW_INDEX, body={
            "size": 100,
            "sort": [{"@timestamp": "asc"}],
            "_source": ["message", "@timestamp", "src_ip"],
            "query": {"bool": {"must": [
                {"term": {"src_ip.keyword": src_ip}},
                {"range": {"@timestamp": {
                    "gte": f"{ts}||-{SESSION_WINDOW_MINUTES}m",
                    "lte": f"{ts}||+{SESSION_WINDOW_MINUTES}m",
                }}}
            ]}}
        })
        messages = [h["_source"].get("message", "") for h in res["hits"]["hits"]]

        if not messages:
            return f"No session logs found for IP {src_ip}.", {}

        total   = len(messages)
        failed  = sum(1 for m in messages if any(k in m.lower() for k in ["failed","invalid","error","denied","refused"]))
        success = sum(1 for m in messages if any(k in m.lower() for k in ["accepted","success","opened","session opened"]))
        sudo    = sum(1 for m in messages if "sudo" in m.lower() or "su " in m.lower())
        wget    = sum(1 for m in messages if any(k in m.lower() for k in ["wget","curl","download","http","ftp"]))
        cron    = sum(1 for m in messages if "cron" in m.lower())
        root    = sum(1 for m in messages if "root" in m.lower())

        stats   = {"failed": failed, "success": success, "sudo": sudo, "wget": wget}
        ratio   = round(failed / total * 100, 1) if total > 0 else 0

        summary  = f"=== Behavioral session for IP {src_ip} (±{SESSION_WINDOW_MINUTES} min) ===\n"
        summary += f"Total events      : {total}\n"
        summary += f"Failed/denied     : {failed}\n"
        summary += f"Successful auth   : {success}\n"
        summary += f"Sudo/su events    : {sudo}\n"
        summary += f"Download activity : {wget}\n"
        summary += f"Cron activity     : {cron}\n"
        summary += f"Root references   : {root}\n"
        summary += f"Failure ratio     : {ratio}%\n"

        summary += f"\nChronological events ({min(total, 10)} of {total}):\n"
        shown = messages[:5] + (["  [... more events ...]"] if total > 10 else []) + (messages[-5:] if total > 10 else [])
        for i, m in enumerate(shown):
            summary += f"  [{i+1}] {m[:120]}\n"

        return summary, stats

    except Exception as e:
        return f"Session fetch error: {e}", {}


def _get_time_neighbors(ts: str) -> str:
    try:
        res = es.search(index=RAW_INDEX, body={
            "size": 15,
            "sort": [{"@timestamp": "asc"}],
            "_source": ["message", "@timestamp"],
            "query": {"range": {"@timestamp": {
                "gte": f"{ts}||-2m",
                "lte": f"{ts}||+2m",
            }}}
        })
        neighbors = [h["_source"].get("message", "") for h in res["hits"]["hits"]]
        return "=== Time-window neighbors (±2 min) ===\n" + "\n".join(neighbors)
    except Exception as e:
        return f"Context fetch error: {e}"


# ── LLM call — routes to configured provider ──────────────────────────────────
def call_llm(log_line: str, mitre_ctx: str, session_ctx: str, baseline_ctx: str) -> tuple:
    baseline_section = f"\nBehavioral baseline deviation:\n{baseline_ctx}\n" if baseline_ctx else ""

    prompt = f"""You are a senior security analyst specializing in threat detection.

MITRE ATT&CK and Sigma detection rules most relevant to this log:
{mitre_ctx}

Behavioral session context for this source:
{session_ctx}
{baseline_section}
Log entry under analysis:
{log_line}

Analyze the log entry using the session context and baseline deviation.
Consider: failure ratios, attack progression, baseline anomalies, MITRE patterns.

Reply in this exact format:
THREAT_DETECTED: YES or NO
ATTACK_TYPE: specific technique name, or NONE
MITRE_ID: MITRE technique ID, or NONE
CONFIDENCE: HIGH or MEDIUM or LOW
REASONING: Two to three sentences explaining your conclusion."""

    try:
        if LLM_PROVIDER == "ollama":
            resp = requests.post(
                f"{OLLAMA_HOST}/api/chat",
                json={
                    "model"  : OLLAMA_MODEL,
                    "messages": [
                        {"role": "user",      "content": prompt},
                        {"role": "assistant", "content": "THREAT_DETECTED:"},
                    ],
                    "stream" : False,
                    "think"  : False,
                    "options": {"temperature": 0, "num_predict": 300},
                },
                timeout=180,
            )
            raw = "THREAT_DETECTED:" + resp.json().get("message", {}).get("content", "").strip()

        elif LLM_PROVIDER == "deepseek":
            resp = requests.post(
                "https://api.deepseek.com/chat/completions",
                headers={"Authorization": f"Bearer {DS_API_KEY}", "Content-Type": "application/json"},
                json={
                    "model"      : "deepseek-chat",
                    "messages"   : [{"role": "user", "content": prompt}],
                    "temperature": 0,
                    "max_tokens" : 300,
                },
                timeout=60,
            )
            raw = resp.json()["choices"][0]["message"]["content"].strip()
            if not raw.startswith("THREAT_DETECTED:"):
                raw = "THREAT_DETECTED:" + raw

        elif LLM_PROVIDER == "claude":
            resp = requests.post(
                "https://api.anthropic.com/v1/messages",
                headers={
                    "x-api-key"        : CL_API_KEY,
                    "anthropic-version": "2023-06-01",
                    "Content-Type"     : "application/json",
                },
                json={
                    "model"     : CL_MODEL,
                    "max_tokens": 300,
                    "messages"  : [{"role": "user", "content": prompt}],
                },
                timeout=60,
            )
            raw = resp.json()["content"][0]["text"].strip()
            if not raw.startswith("THREAT_DETECTED:"):
                raw = "THREAT_DETECTED:" + raw

        else:
            return "ERROR", "ERROR", "NONE", "LOW", f"Unknown LLM provider: {LLM_PROVIDER}"

        # Parse response
        verdict = "NO"; attack = "NONE"; mitre_id = "NONE"
        confidence = "LOW"; reasoning = "NONE"

        for line in raw.splitlines():
            l = line.strip()
            if l.startswith("THREAT_DETECTED:"):
                verdict = "YES" if "YES" in l.upper() else "NO"
            elif l.startswith("ATTACK_TYPE:"):
                attack = l.split(":", 1)[1].strip()
            elif l.startswith("MITRE_ID:"):
                mitre_id = l.split(":", 1)[1].strip()
            elif l.startswith("CONFIDENCE:"):
                confidence = l.split(":", 1)[1].strip().upper()
            elif l.startswith("REASONING:"):
                reasoning = l.split(":", 1)[1].strip()

        return verdict, attack, mitre_id, confidence, reasoning

    except Exception as e:
        return "ERROR", "ERROR", "NONE", "LOW", str(e)


# ── Write verdict back to ES ──────────────────────────────────────────────────
def write_verdict(hit: dict, verdict: str, attack: str, mitre_id: str, confidence: str, reasoning: str):
    doc_id = hit["_id"]
    index  = hit["_index"]
    src    = hit["_source"]

    # Always mark original as analyzed
    try:
        es.update(index=index, id=doc_id, body={"doc": {
            "llm_analyzed" : "true",
            "llm_verdict"  : verdict,
            "attack_type"  : attack,
            "mitre_id"     : mitre_id,
            "confidence"   : confidence,
            "llm_reasoning": reasoning,
        }})
    except Exception as e:
        print(f"  [!] Failed to update {doc_id}: {e}")

    if verdict != "YES":
        return

    # Route by confidence
    confidence_rank = {"HIGH": 3, "MEDIUM": 2, "LOW": 1}
    threshold_rank  = confidence_rank.get(MIN_CONFIDENCE, 3)
    current_rank    = confidence_rank.get(confidence, 0)

    if current_rank >= threshold_rank:
        target = OUT_INDEX
    elif confidence == "MEDIUM":
        target = REVIEW_INDEX
    else:
        return  # LOW — discard

    try:
        es.index(index=target, document={
            "@timestamp"   : src.get("@timestamp"),
            "message"      : src.get("message"),
            "src_ip"       : src.get("src_ip"),
            "llm_verdict"  : verdict,
            "attack_type"  : attack,
            "mitre_id"     : mitre_id,
            "confidence"   : confidence,
            "llm_reasoning": reasoning,
            "log_type"     : LOG_TYPE,
        })
    except Exception as e:
        print(f"  [!] Failed to write to {target}: {e}")


# ── Main poll loop ────────────────────────────────────────────────────────────
def run():
    print("=" * 60)
    print("  RAG Threat Detector — Live Analysis")
    print("  Ctrl+C to stop")
    print("=" * 60 + "\n")

    analyzed = threats = errors = 0

    while True:
        try:
            res  = es.search(index=RAW_INDEX, body={
                "size": 10,
                "sort": [{"@timestamp": "asc"}],
                "query": {"term": {"llm_analyzed": "false"}},
            })
            hits = res["hits"]["hits"]
        except Exception as e:
            print(f"[!] ES error: {e}")
            time.sleep(POLL_EVERY)
            continue

        if not hits:
            print(f"\r  Waiting... analyzed={analyzed} threats={threats} errors={errors}",
                  end="", flush=True)
            time.sleep(POLL_EVERY)
            continue

        for hit in hits:
            log_line = hit["_source"].get("message", "").strip()
            src_ip   = hit["_source"].get("src_ip", "")
            if not log_line:
                continue

            analyzed += 1
            print(f"\n  [{analyzed}] {log_line[:80]}...")

            session_ctx, session_stats = get_session(hit)
            mitre_ctx    = retrieve_mitre(log_line)
            baseline_ctx = baseline.get_context(src_ip, session_stats)

            verdict, attack, mitre_id, confidence, reasoning = call_llm(
                log_line, mitre_ctx, session_ctx, baseline_ctx
            )

            if verdict == "ERROR":
                errors += 1
                print(f"  ✗ ERROR   | {reasoning[:60]}")
            elif verdict == "YES":
                threats += 1
                print(f"  ⚠  THREAT [{confidence}] | {attack} {mitre_id}")
                print(f"  ↳ {reasoning[:120]}")
            else:
                print(f"  ✓ CLEAN   | confidence={confidence}")

            write_verdict(hit, verdict, attack, mitre_id, confidence, reasoning)

        time.sleep(POLL_EVERY)


if __name__ == "__main__":
    run()
