"""
main.py
=======
Main entry point for RAG Threat Detector.
Reads config.yaml generated by setup_wizard.py and starts the pipeline.

Usage:
    python main.py                  # start live analysis
    python main.py --setup          # run setup wizard
    python main.py --build-rag      # rebuild MITRE+Sigma knowledge base
    python main.py --evaluate <csv> # evaluate against ground truth
"""

import sys
import os
import yaml
import time
import argparse
import requests
import chromadb
from pathlib import Path
from datetime import datetime, timezone, timedelta
from elasticsearch import Elasticsearch
from sentence_transformers import SentenceTransformer
from baseline import BaselineModel

CONFIG_FILE = "./config.yaml"


def load_config() -> dict:
    if not Path(CONFIG_FILE).exists():
        print(f"[!] Config file not found: {CONFIG_FILE}")
        print("    Run setup first: python main.py --setup")
        sys.exit(1)
    with open(CONFIG_FILE) as f:
        return yaml.safe_load(f)


def build_es_client(cfg: dict) -> Elasticsearch:
    es_cfg = cfg["elasticsearch"]
    host   = es_cfg["host"]
    user   = es_cfg.get("username", "")
    pwd    = es_cfg.get("password", "")
    if user and pwd:
        return Elasticsearch(host, basic_auth=(user, pwd))
    return Elasticsearch(host)


def call_llm(cfg: dict, prompt: str) -> str:
    """Route LLM call to configured provider."""
    llm = cfg["llm"]
    provider = llm["provider"]

    if provider == "ollama":
        resp = requests.post(
            f"{llm['ollama_host']}/api/chat",
            json={
                "model"  : llm["ollama_model"],
                "messages": [
                    {"role": "user",      "content": prompt},
                    {"role": "assistant", "content": "THREAT_DETECTED:"},
                ],
                "stream" : False,
                "think"  : False,
                "options": {"temperature": 0, "num_predict": 300},
            },
            timeout=180,
        )
        raw = resp.json().get("message", {}).get("content", "").strip()

    elif provider == "deepseek":
        resp = requests.post(
            "https://api.deepseek.com/chat/completions",
            headers={
                "Authorization": f"Bearer {llm['deepseek_api_key']}",
                "Content-Type" : "application/json",
            },
            json={
                "model"      : "deepseek-chat",
                "messages"   : [{"role": "user", "content": prompt}],
                "temperature": 0,
                "max_tokens" : 300,
            },
            timeout=60,
        )
        raw = resp.json()["choices"][0]["message"]["content"].strip()
        # Strip "THREAT_DETECTED:" prefix for consistency
        if not raw.startswith("THREAT_DETECTED:"):
            raw = "THREAT_DETECTED:" + raw

    elif provider == "claude":
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key"        : llm["claude_api_key"],
                "anthropic-version": "2023-06-01",
                "Content-Type"     : "application/json",
            },
            json={
                "model"     : llm.get("claude_model", "claude-sonnet-4-6"),
                "max_tokens": 300,
                "messages"  : [{"role": "user", "content": prompt}],
            },
            timeout=60,
        )
        raw = resp.json()["content"][0]["text"].strip()
        if not raw.startswith("THREAT_DETECTED:"):
            raw = "THREAT_DETECTED:" + raw

    else:
        raise ValueError(f"Unknown LLM provider: {provider}")

    return "THREAT_DETECTED:" + raw if not raw.startswith("THREAT_DETECTED:") else raw


def parse_llm_response(raw: str) -> tuple:
    verdict = "NO"; attack = "NONE"; mitre_id = "NONE"
    confidence = "LOW"; reasoning = "NONE"
    for line in raw.splitlines():
        l = line.strip()
        if l.startswith("THREAT_DETECTED:"):
            verdict = "YES" if "YES" in l.upper() else "NO"
        elif l.startswith("ATTACK_TYPE:"):
            attack = l.split(":", 1)[1].strip()
        elif l.startswith("MITRE_ID:"):
            mitre_id = l.split(":", 1)[1].strip()
        elif l.startswith("CONFIDENCE:"):
            confidence = l.split(":", 1)[1].strip().upper()
        elif l.startswith("REASONING:"):
            reasoning = l.split(":", 1)[1].strip()
    return verdict, attack, mitre_id, confidence, reasoning


def run(cfg: dict):
    """Main analysis loop."""
    es       = build_es_client(cfg)
    rag_cfg  = cfg["rag"]
    ana_cfg  = cfg["analysis"]
    out_cfg  = cfg["output"]
    raw_idx  = cfg["elasticsearch"]["index"]
    out_idx  = out_cfg["analyzed_index"]

    session_window = ana_cfg["session_window_minutes"]
    poll_interval  = ana_cfg["poll_interval_seconds"]
    top_k          = ana_cfg["top_k_chunks"]

    # ── Init RAG ──────────────────────────────────────────────────────────────
    print("Loading RAG knowledge base...")
    embedder   = SentenceTransformer(rag_cfg["embed_model"])
    chroma     = chromadb.PersistentClient(path=rag_cfg["db_path"])
    collection = chroma.get_collection(rag_cfg["collection"])
    print(f"  {collection.count()} entries loaded")

    # ── Init baseline ─────────────────────────────────────────────────────────
    baseline = BaselineModel(es)
    if not baseline.load("./baseline.json"):
        b_cfg  = cfg["baseline"]
        before = b_cfg.get("before")
        hours  = b_cfg.get("hours", 2)
        if b_cfg["mode"] == "auto" or not before:
            before = datetime.now(timezone.utc).isoformat()
        baseline.build(index=raw_idx, hours=hours, before_timestamp=before)
        baseline.save("./baseline.json")

    # ── Print startup info ────────────────────────────────────────────────────
    llm_label = cfg["llm"]["provider"]
    if llm_label == "ollama":
        llm_label += f" / {cfg['llm']['ollama_model']}"

    print(f"""
{'='*60}
  RAG Threat Detector — Running
  Log server : {cfg['elasticsearch']['host']}
  Index      : {raw_idx}
  LLM        : {llm_label}
  Session    : ±{session_window} min
  Baseline   : {len(baseline.baseline)} IPs profiled
  Output     : {out_idx}
  Ctrl+C to stop
{'='*60}
""")

    analyzed = threats = errors = 0

    while True:
        query = {
            "size": 10,
            "sort": [{"@timestamp": "asc"}],
            "query": {"term": {"llm_analyzed": "false"}},
        }

        try:
            res  = es.search(index=raw_idx, body=query)
            hits = res["hits"]["hits"]
        except Exception as e:
            print(f"[!] ES error: {e}")
            time.sleep(poll_interval)
            continue

        if not hits:
            print(f"\r  Waiting... analyzed={analyzed} threats={threats} errors={errors}",
                  end="", flush=True)
            time.sleep(poll_interval)
            continue

        for hit in hits:
            log_line = hit["_source"].get("message", "").strip()
            src_ip   = hit["_source"].get("src_ip", "")
            ts       = hit["_source"].get("@timestamp", "")
            if not log_line:
                continue

            analyzed += 1
            print(f"\n  [{analyzed}] {log_line[:80]}...")

            # Session context
            session_ctx, session_stats = _get_session(
                es, raw_idx, src_ip, ts, session_window
            )

            # MITRE + Sigma RAG
            vec      = embedder.encode(log_line).tolist()
            rag_res  = collection.query(query_embeddings=[vec], n_results=top_k)
            mitre_ctx = "\n".join(
                f"[{rag_res['metadatas'][0][i]['id']}] "
                f"{rag_res['metadatas'][0][i]['technique']} "
                f"({rag_res['metadatas'][0][i]['tactic']}): "
                f"{rag_res['documents'][0][i][:150]}"
                for i in range(len(rag_res["ids"][0]))
            )

            # Baseline context
            baseline_ctx = baseline.get_context(src_ip, session_stats)

            # Build prompt
            baseline_section = f"\nBehavioral baseline:\n{baseline_ctx}\n" if baseline_ctx else ""
            prompt = f"""You are a senior security analyst specializing in threat detection.

MITRE ATT&CK and Sigma detection rules most relevant to this log:
{mitre_ctx}

Behavioral session context:
{session_ctx}
{baseline_section}
Log entry under analysis:
{log_line}

Analyze whether this log entry is part of malicious activity.
Consider session patterns, baseline deviations, and matching detection rules.

Reply in this exact format:
THREAT_DETECTED: YES or NO
ATTACK_TYPE: technique name or NONE
MITRE_ID: technique ID or NONE
CONFIDENCE: HIGH or MEDIUM or LOW
REASONING: Two sentences explaining your conclusion."""

            try:
                raw_resp = call_llm(cfg, prompt)
                verdict, attack, mitre_id, confidence, reasoning = parse_llm_response(raw_resp)
            except Exception as e:
                errors += 1
                print(f"  ✗ LLM error: {e}")
                _mark_analyzed(es, hit, "ERROR", "ERROR", "NONE", "LOW", str(e))
                continue

            if verdict == "YES":
                threats += 1
                print(f"  ⚠  THREAT [{confidence}] | {attack} {mitre_id}")
                print(f"  ↳ {reasoning[:120]}")
            else:
                print(f"  ✓ CLEAN   | confidence={confidence}")

            _mark_analyzed(es, hit, verdict, attack, mitre_id, confidence, reasoning)

            if verdict == "YES":
                try:
                    es.index(index=out_idx, document={
                        "@timestamp"   : hit["_source"].get("@timestamp"),
                        "message"      : log_line,
                        "src_ip"       : src_ip,
                        "llm_verdict"  : verdict,
                        "attack_type"  : attack,
                        "mitre_id"     : mitre_id,
                        "confidence"   : confidence,
                        "llm_reasoning": reasoning,
                    })
                except Exception:
                    pass

        time.sleep(poll_interval)


def _get_session(es, index, src_ip, ts, window_minutes):
    if not src_ip:
        return "No source IP — no session context.", {}
    try:
        res = es.search(index=index, body={
            "size": 100,
            "sort": [{"@timestamp": "asc"}],
            "_source": ["message", "@timestamp"],
            "query": {"bool": {"must": [
                {"term": {"src_ip.keyword": src_ip}},
                {"range": {"@timestamp": {
                    "gte": f"{ts}||-{window_minutes}m",
                    "lte": f"{ts}||+{window_minutes}m",
                }}}
            ]}}
        })
        messages = [h["_source"].get("message", "") for h in res["hits"]["hits"]]
        if not messages:
            return f"No session logs for {src_ip}.", {}

        total   = len(messages)
        failed  = sum(1 for m in messages if any(k in m.lower() for k in ["failed","invalid","denied","refused"]))
        success = sum(1 for m in messages if any(k in m.lower() for k in ["accepted","success","opened"]))
        sudo    = sum(1 for m in messages if "sudo" in m.lower())
        wget    = sum(1 for m in messages if any(k in m.lower() for k in ["wget","curl","download"]))

        stats   = {"failed": failed, "success": success, "sudo": sudo, "wget": wget}
        ratio   = round(failed / total * 100, 1) if total > 0 else 0

        summary  = f"=== Session for {src_ip} (±{window_minutes}min) ===\n"
        summary += f"Total={total} Failed={failed} Success={success} Sudo={sudo} Downloads={wget} FailRatio={ratio}%\n"
        shown    = messages[:5] + (["[...]"] if total > 10 else []) + (messages[-5:] if total > 10 else [])
        for i, m in enumerate(shown):
            summary += f"  [{i+1}] {m[:120]}\n"

        return summary, stats
    except Exception as e:
        return f"Session error: {e}", {}


def _mark_analyzed(es, hit, verdict, attack, mitre_id, confidence, reasoning):
    try:
        es.update(index=hit["_index"], id=hit["_id"], body={"doc": {
            "llm_analyzed" : "true",
            "llm_verdict"  : verdict,
            "attack_type"  : attack,
            "mitre_id"     : mitre_id,
            "confidence"   : confidence,
            "llm_reasoning": reasoning,
        }})
    except Exception:
        pass


def main():
    parser = argparse.ArgumentParser(description="RAG Threat Detector")
    parser.add_argument("--setup",    action="store_true", help="Run setup wizard")
    parser.add_argument("--build-rag",action="store_true", help="Rebuild MITRE+Sigma knowledge base")
    parser.add_argument("--evaluate", metavar="CSV",       help="Evaluate against ground truth CSV")
    args = parser.parse_args()

    if args.setup:
        from setup_wizard import run_wizard
        run_wizard()

    elif args.build_rag:
        import subprocess
        subprocess.run([sys.executable, "build_chromadb_with_sigma.py"])

    elif args.evaluate:
        import subprocess
        subprocess.run([sys.executable, "evaluate.py", args.evaluate])

    else:
        cfg = load_config()
        run(cfg)


if __name__ == "__main__":
    main()
